// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcydykuwzvlfzhuiuzts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjeWR5a3V3enZsZnpodWl1enRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MjM3MDksImV4cCI6MjA1NTQ5OTcwOX0.IZV9HH4d8q-FviiGB7Qeb3G0_l0qPKpfFe8BdBg1dcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);