
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcydykuwzvlfzhuiuzts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjeWR5a3V3enZsZnpodWl1enRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MjM3MDksImV4cCI6MjA1NTQ5OTcwOX0.IZV9HH4d8q-FviiGB7Qeb3G0_l0qPKpfFe8BdBg1dcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper functions for auth
export const getCurrentUser = async () => {
  const { data: { user } } = await supabase.auth.getUser();
  return user;
};

export const getUserProfile = async (userId: string) => {
  const { data, error } = await supabase
    .from('profiles')
    .select('*')
    .eq('id', userId)
    .single();
  
  if (error) {
    console.error('Error fetching user profile:', error);
    return null;
  }
  
  return data;
};

// Helper functions for data operations
export const fetchData = async (table: string, options = {}) => {
  const query = supabase.from(table).select('*');
  const { data, error } = await query;
  
  if (error) {
    console.error(`Error fetching data from ${table}:`, error);
    return [];
  }
  
  return data || [];
};

export const insertData = async (table: string, data: any) => {
  const { data: result, error } = await supabase
    .from(table)
    .insert(data)
    .select();
  
  if (error) {
    console.error(`Error inserting data into ${table}:`, error);
    throw error;
  }
  
  return result;
};

export const updateData = async (table: string, id: string, data: any) => {
  const { data: result, error } = await supabase
    .from(table)
    .update(data)
    .eq('id', id)
    .select();
  
  if (error) {
    console.error(`Error updating data in ${table}:`, error);
    throw error;
  }
  
  return result;
};

export const deleteData = async (table: string, id: string) => {
  const { error } = await supabase
    .from(table)
    .delete()
    .eq('id', id);
  
  if (error) {
    console.error(`Error deleting data from ${table}:`, error);
    throw error;
  }
  
  return true;
};
